// Generated by gencpp from file perception_msgs/DriveArea.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_DRIVEAREA_H
#define PERCEPTION_MSGS_MESSAGE_DRIVEAREA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct DriveArea_
{
  typedef DriveArea_<ContainerAllocator> Type;

  DriveArea_()
    : header()
    , left_area_avail(false)
    , right_area_avail(false)  {
    }
  DriveArea_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_area_avail(false)
    , right_area_avail(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _left_area_avail_type;
  _left_area_avail_type left_area_avail;

   typedef uint8_t _right_area_avail_type;
  _right_area_avail_type right_area_avail;





  typedef boost::shared_ptr< ::perception_msgs::DriveArea_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::DriveArea_<ContainerAllocator> const> ConstPtr;

}; // struct DriveArea_

typedef ::perception_msgs::DriveArea_<std::allocator<void> > DriveArea;

typedef boost::shared_ptr< ::perception_msgs::DriveArea > DriveAreaPtr;
typedef boost::shared_ptr< ::perception_msgs::DriveArea const> DriveAreaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::DriveArea_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::DriveArea_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'perception_msgs': ['/home/oligay_61/zone3/src/message/perception_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::DriveArea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::DriveArea_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::DriveArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::DriveArea_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::DriveArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::DriveArea_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::DriveArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d7db88ce8a43d4073cc44d916824e19";
  }

  static const char* value(const ::perception_msgs::DriveArea_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d7db88ce8a43d40ULL;
  static const uint64_t static_value2 = 0x73cc44d916824e19ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::DriveArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/DriveArea";
  }

  static const char* value(const ::perception_msgs::DriveArea_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::DriveArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
bool left_area_avail\n\
bool right_area_avail\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::perception_msgs::DriveArea_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::DriveArea_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_area_avail);
      stream.next(m.right_area_avail);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveArea_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::DriveArea_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::DriveArea_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_area_avail: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_area_avail);
    s << indent << "right_area_avail: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_area_avail);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_DRIVEAREA_H
