// Generated by gencpp from file kalman_msgs/Kinematics.msg
// DO NOT EDIT!


#ifndef KALMAN_MSGS_MESSAGE_KINEMATICS_H
#define KALMAN_MSGS_MESSAGE_KINEMATICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kalman_msgs
{
template <class ContainerAllocator>
struct Kinematics_
{
  typedef Kinematics_<ContainerAllocator> Type;

  Kinematics_()
    : header()
    , k_vx(0.0)
    , k_ax(0.0)
    , k_yawrate(0.0)  {
    }
  Kinematics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , k_vx(0.0)
    , k_ax(0.0)
    , k_yawrate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _k_vx_type;
  _k_vx_type k_vx;

   typedef double _k_ax_type;
  _k_ax_type k_ax;

   typedef double _k_yawrate_type;
  _k_yawrate_type k_yawrate;





  typedef boost::shared_ptr< ::kalman_msgs::Kinematics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kalman_msgs::Kinematics_<ContainerAllocator> const> ConstPtr;

}; // struct Kinematics_

typedef ::kalman_msgs::Kinematics_<std::allocator<void> > Kinematics;

typedef boost::shared_ptr< ::kalman_msgs::Kinematics > KinematicsPtr;
typedef boost::shared_ptr< ::kalman_msgs::Kinematics const> KinematicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kalman_msgs::Kinematics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kalman_msgs::Kinematics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kalman_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'kalman_msgs': ['/home/oligay_61/zone3/src/message/kalman_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kalman_msgs::Kinematics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kalman_msgs::Kinematics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman_msgs::Kinematics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kalman_msgs::Kinematics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_msgs::Kinematics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kalman_msgs::Kinematics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kalman_msgs::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "067f61bc5c7b18e4250103299afbefa6";
  }

  static const char* value(const ::kalman_msgs::Kinematics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x067f61bc5c7b18e4ULL;
  static const uint64_t static_value2 = 0x250103299afbefa6ULL;
};

template<class ContainerAllocator>
struct DataType< ::kalman_msgs::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kalman_msgs/Kinematics";
  }

  static const char* value(const ::kalman_msgs::Kinematics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kalman_msgs::Kinematics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# kalman_vx\n\
#  >0 for forward, <0 for backward\n\
float64 k_vx\n\
\n\
# kalman_ax\n\
#  >0 for vx up, <0 for vx down\n\
float64 k_ax\n\
\n\
# kalman_yawrate\n\
float64 k_yawrate \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::kalman_msgs::Kinematics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kalman_msgs::Kinematics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.k_vx);
      stream.next(m.k_ax);
      stream.next(m.k_yawrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Kinematics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kalman_msgs::Kinematics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kalman_msgs::Kinematics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "k_vx: ";
    Printer<double>::stream(s, indent + "  ", v.k_vx);
    s << indent << "k_ax: ";
    Printer<double>::stream(s, indent + "  ", v.k_ax);
    s << indent << "k_yawrate: ";
    Printer<double>::stream(s, indent + "  ", v.k_yawrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KALMAN_MSGS_MESSAGE_KINEMATICS_H
