Header header

uint8 auto_mode
uint8 engine_active
uint8 hand_brake_active
uint8 EBS_active
uint8 retarder_active
uint8 EPS_active
uint8 hang_active

uint8 left_light
uint8 right_light
uint8 near_light
uint8 far_light
uint8 top_warning_light
uint8 air_beep
uint8 front_fog_light
uint8 front_work_light
uint8 side_light
uint8 position_light
uint8 back_left_light
uint8 back_right_light
uint8 back_position_light
uint8 brake_light
uint8 reverse_light
uint8 back_work_light

float64 air_pressure1
float64 air_pressure2
float64 oil_percentage

uint8 cooler1
uint8 cooler2
uint8 axle_diff_switch
uint8 drier_power
uint8 inclinometer_power
uint8 cold_water_treasure_power
uint8 exhaust_brake_switch
uint8 sweeper_power
uint8 EBS_power
uint8 air_pressure_power
uint8 hang_up_power
uint8 hang_down_power
uint8 hang_manual_power