// Generated by gencpp from file planner_msgs/PlannerFSM.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNERFSM_H
#define PLANNER_MSGS_MESSAGE_PLANNERFSM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct PlannerFSM_
{
  typedef PlannerFSM_<ContainerAllocator> Type;

  PlannerFSM_()
    : header()
    , gear(0)
    , planner_fsm(0)
    , last_planner_fsm(0)  {
    }
  PlannerFSM_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gear(0)
    , planner_fsm(0)
    , last_planner_fsm(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _gear_type;
  _gear_type gear;

   typedef int32_t _planner_fsm_type;
  _planner_fsm_type planner_fsm;

   typedef int32_t _last_planner_fsm_type;
  _last_planner_fsm_type last_planner_fsm;





  typedef boost::shared_ptr< ::planner_msgs::PlannerFSM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::PlannerFSM_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerFSM_

typedef ::planner_msgs::PlannerFSM_<std::allocator<void> > PlannerFSM;

typedef boost::shared_ptr< ::planner_msgs::PlannerFSM > PlannerFSMPtr;
typedef boost::shared_ptr< ::planner_msgs::PlannerFSM const> PlannerFSMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::PlannerFSM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::PlannerFSM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'planner_msgs': ['/home/oligay_61/zone3/src/message/planner_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::PlannerFSM_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::PlannerFSM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::PlannerFSM_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6df5be79c813c24a6414911b5ba25621";
  }

  static const char* value(const ::planner_msgs::PlannerFSM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6df5be79c813c24aULL;
  static const uint64_t static_value2 = 0x6414911b5ba25621ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/PlannerFSM";
  }

  static const char* value(const ::planner_msgs::PlannerFSM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int32 gear\n\
int32 planner_fsm\n\
int32 last_planner_fsm\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::planner_msgs::PlannerFSM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gear);
      stream.next(m.planner_fsm);
      stream.next(m.last_planner_fsm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerFSM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::PlannerFSM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::PlannerFSM_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
    s << indent << "planner_fsm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.planner_fsm);
    s << indent << "last_planner_fsm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.last_planner_fsm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNERFSM_H
