// Generated by gencpp from file planner_msgs/StopGo.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_STOPGO_H
#define PLANNER_MSGS_MESSAGE_STOPGO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct StopGo_
{
  typedef StopGo_<ContainerAllocator> Type;

  StopGo_()
    : header()
    , stop_or_go()  {
    }
  StopGo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stop_or_go(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _stop_or_go_type;
  _stop_or_go_type stop_or_go;





  typedef boost::shared_ptr< ::planner_msgs::StopGo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::StopGo_<ContainerAllocator> const> ConstPtr;

}; // struct StopGo_

typedef ::planner_msgs::StopGo_<std::allocator<void> > StopGo;

typedef boost::shared_ptr< ::planner_msgs::StopGo > StopGoPtr;
typedef boost::shared_ptr< ::planner_msgs::StopGo const> StopGoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::StopGo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::StopGo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'planner_msgs': ['/home/oligay_61/zone3/src/message/planner_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::StopGo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::StopGo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::StopGo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::StopGo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::StopGo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::StopGo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::StopGo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baf7a56f493b276b6a53976d92a68e99";
  }

  static const char* value(const ::planner_msgs::StopGo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaf7a56f493b276bULL;
  static const uint64_t static_value2 = 0x6a53976d92a68e99ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::StopGo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/StopGo";
  }

  static const char* value(const ::planner_msgs::StopGo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::StopGo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# stop or go\n\
string stop_or_go\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::planner_msgs::StopGo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::StopGo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stop_or_go);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopGo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::StopGo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::StopGo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stop_or_go: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.stop_or_go);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_STOPGO_H
