// Generated by gencpp from file planner_msgs/WayPoints.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_WAYPOINTS_H
#define PLANNER_MSGS_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <planner_msgs/WayPoint.h>

namespace planner_msgs
{
template <class ContainerAllocator>
struct WayPoints_
{
  typedef WayPoints_<ContainerAllocator> Type;

  WayPoints_()
    : header()
    , coord_type()
    , control_type()
    , planner_fsm()
    , points()  {
    }
  WayPoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coord_type(_alloc)
    , control_type(_alloc)
    , planner_fsm(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _coord_type_type;
  _coord_type_type coord_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _control_type_type;
  _control_type_type control_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _planner_fsm_type;
  _planner_fsm_type planner_fsm;

   typedef std::vector< ::planner_msgs::WayPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planner_msgs::WayPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::planner_msgs::WayPoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::WayPoints_<ContainerAllocator> const> ConstPtr;

}; // struct WayPoints_

typedef ::planner_msgs::WayPoints_<std::allocator<void> > WayPoints;

typedef boost::shared_ptr< ::planner_msgs::WayPoints > WayPointsPtr;
typedef boost::shared_ptr< ::planner_msgs::WayPoints const> WayPointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::WayPoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::WayPoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'planner_msgs': ['/home/oligay_61/zone3/src/message/planner_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::WayPoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::WayPoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::WayPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::WayPoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::WayPoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::WayPoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5fe65fd9eca45e86d5dc3de0bdfc36bc";
  }

  static const char* value(const ::planner_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5fe65fd9eca45e86ULL;
  static const uint64_t static_value2 = 0xd5dc3de0bdfc36bcULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/WayPoints";
  }

  static const char* value(const ::planner_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::WayPoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# all of the waypoints are in ego coordinate system\n\
# coord_type = \"ego\"\n\
# track use enu, and is sended to rviz\n\
# coord_type = \"enu\"\n\
string coord_type\n\
\n\
# \"teledrive\" or \"follow_tracks\"\n\
string control_type\n\
\n\
string planner_fsm\n\
\n\
WayPoint[] points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: planner_msgs/WayPoint\n\
# point has no Header\n\
\n\
int32 lock_down_index\n\
int32 pt_index\n\
\n\
float64 x\n\
float64 y \n\
float64 z\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
float64 kalman_yawrate\n\
\n\
float64 kalman_vx\n\
float64 acceleration\n\
\n\
# teledrive, share gear, xbr\n\
float64 steer\n\
float64 throttle_percentage\n\
float64 xbr\n\
int8 gear\n\
\n\
uint8 left_light\n\
uint8 right_light\n\
#uint8 emergency_light\n\
uint8 air_beep\n\
\n\
float64 time_to_last_point\n\
float64 current_lat_error\n\
float64 current_lng_error\n\
bool flag_lock_down_index_offload\n\
";
  }

  static const char* value(const ::planner_msgs::WayPoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::WayPoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coord_type);
      stream.next(m.control_type);
      stream.next(m.planner_fsm);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WayPoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::WayPoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::WayPoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coord_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.coord_type);
    s << indent << "control_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.control_type);
    s << indent << "planner_fsm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.planner_fsm);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner_msgs::WayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_WAYPOINTS_H
