(cl:in-package tli65_can_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          TOP_WARNING_LIGHT-VAL
          TOP_WARNING_LIGHT
          AIR_BEEP-VAL
          AIR_BEEP
          FRONT_FOG_LIGHT-VAL
          FRONT_FOG_LIGHT
          FRONT_WORK_LIGHT-VAL
          FRONT_WORK_LIGHT
          SIDE_LIGHT-VAL
          SIDE_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          SWEEPER_POWER-VAL
          SWEEPER_POWER
          EBS_POWER-VAL
          EBS_POWER
          AIR_PRESSURE_POWER-VAL
          AIR_PRESSURE_POWER
          HANG_UP_POWER-VAL
          HANG_UP_POWER
          HANG_DOWN_POWER-VAL
          HANG_DOWN_POWER
          HANG_MANUAL_POWER-VAL
          HANG_MANUAL_POWER
))