// Generated by gencpp from file decider_msgs/Decider.msg
// DO NOT EDIT!


#ifndef DECIDER_MSGS_MESSAGE_DECIDER_H
#define DECIDER_MSGS_MESSAGE_DECIDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace decider_msgs
{
template <class ContainerAllocator>
struct Decider_
{
  typedef Decider_<ContainerAllocator> Type;

  Decider_()
    : header()
    , lat_strategy()
    , long_strategy()  {
    }
  Decider_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lat_strategy(_alloc)
    , long_strategy(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lat_strategy_type;
  _lat_strategy_type lat_strategy;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _long_strategy_type;
  _long_strategy_type long_strategy;





  typedef boost::shared_ptr< ::decider_msgs::Decider_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::decider_msgs::Decider_<ContainerAllocator> const> ConstPtr;

}; // struct Decider_

typedef ::decider_msgs::Decider_<std::allocator<void> > Decider;

typedef boost::shared_ptr< ::decider_msgs::Decider > DeciderPtr;
typedef boost::shared_ptr< ::decider_msgs::Decider const> DeciderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::decider_msgs::Decider_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::decider_msgs::Decider_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace decider_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'decider_msgs': ['/home/oligay_61/zone3/src/message/decider_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::decider_msgs::Decider_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::decider_msgs::Decider_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decider_msgs::Decider_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::decider_msgs::Decider_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decider_msgs::Decider_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::decider_msgs::Decider_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::decider_msgs::Decider_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e2a07bec75f3a1794cd39cc03b4fbee";
  }

  static const char* value(const ::decider_msgs::Decider_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e2a07bec75f3a17ULL;
  static const uint64_t static_value2 = 0x94cd39cc03b4fbeeULL;
};

template<class ContainerAllocator>
struct DataType< ::decider_msgs::Decider_<ContainerAllocator> >
{
  static const char* value()
  {
    return "decider_msgs/Decider";
  }

  static const char* value(const ::decider_msgs::Decider_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::decider_msgs::Decider_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
string lat_strategy\n\
string long_strategy\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::decider_msgs::Decider_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::decider_msgs::Decider_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lat_strategy);
      stream.next(m.long_strategy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Decider_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::decider_msgs::Decider_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::decider_msgs::Decider_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lat_strategy: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lat_strategy);
    s << indent << "long_strategy: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.long_strategy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DECIDER_MSGS_MESSAGE_DECIDER_H
