# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_msgs/HighspeedControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class HighspeedControl(genpy.Message):
  _md5sum = "091494fefb0d9d1769b9b0a619a55e53"
  _type = "control_msgs/HighspeedControl"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

string control_type
string control_fsm
float64 lat_error

uint8 ignition 
uint8 throttle_active
uint8 throttle_precentage
uint8 XBR_active
float64 XBR
# for Tli65
uint8 steer_active
float64 steer
float64 steer_angle_rate
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','control_type','control_fsm','lat_error','ignition','throttle_active','throttle_precentage','XBR_active','XBR','steer_active','steer','steer_angle_rate']
  _slot_types = ['std_msgs/Header','string','string','float64','uint8','uint8','uint8','uint8','float64','uint8','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,control_type,control_fsm,lat_error,ignition,throttle_active,throttle_precentage,XBR_active,XBR,steer_active,steer,steer_angle_rate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HighspeedControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control_type is None:
        self.control_type = ''
      if self.control_fsm is None:
        self.control_fsm = ''
      if self.lat_error is None:
        self.lat_error = 0.
      if self.ignition is None:
        self.ignition = 0
      if self.throttle_active is None:
        self.throttle_active = 0
      if self.throttle_precentage is None:
        self.throttle_precentage = 0
      if self.XBR_active is None:
        self.XBR_active = 0
      if self.XBR is None:
        self.XBR = 0.
      if self.steer_active is None:
        self.steer_active = 0
      if self.steer is None:
        self.steer = 0.
      if self.steer_angle_rate is None:
        self.steer_angle_rate = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.control_type = ''
      self.control_fsm = ''
      self.lat_error = 0.
      self.ignition = 0
      self.throttle_active = 0
      self.throttle_precentage = 0
      self.XBR_active = 0
      self.XBR = 0.
      self.steer_active = 0
      self.steer = 0.
      self.steer_angle_rate = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.control_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.control_fsm
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d4BdB2d().pack(_x.lat_error, _x.ignition, _x.throttle_active, _x.throttle_precentage, _x.XBR_active, _x.XBR, _x.steer_active, _x.steer, _x.steer_angle_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.control_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_fsm = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.control_fsm = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.lat_error, _x.ignition, _x.throttle_active, _x.throttle_precentage, _x.XBR_active, _x.XBR, _x.steer_active, _x.steer, _x.steer_angle_rate,) = _get_struct_d4BdB2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.control_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.control_fsm
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d4BdB2d().pack(_x.lat_error, _x.ignition, _x.throttle_active, _x.throttle_precentage, _x.XBR_active, _x.XBR, _x.steer_active, _x.steer, _x.steer_angle_rate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.control_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_fsm = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.control_fsm = str[start:end]
      _x = self
      start = end
      end += 37
      (_x.lat_error, _x.ignition, _x.throttle_active, _x.throttle_precentage, _x.XBR_active, _x.XBR, _x.steer_active, _x.steer, _x.steer_angle_rate,) = _get_struct_d4BdB2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_d4BdB2d = None
def _get_struct_d4BdB2d():
    global _struct_d4BdB2d
    if _struct_d4BdB2d is None:
        _struct_d4BdB2d = struct.Struct("<d4BdB2d")
    return _struct_d4BdB2d
