// Generated by gencpp from file control_msgs/ControlFSM.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_CONTROLFSM_H
#define CONTROL_MSGS_MESSAGE_CONTROLFSM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace control_msgs
{
template <class ContainerAllocator>
struct ControlFSM_
{
  typedef ControlFSM_<ContainerAllocator> Type;

  ControlFSM_()
    : header()
    , control_fsm(0)
    , last_control_fsm(0)
    , flag_follow_tracks_plannerON(false)
    , gear(0)
    , planner_fsm(0)  {
    }
  ControlFSM_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control_fsm(0)
    , last_control_fsm(0)
    , flag_follow_tracks_plannerON(false)
    , gear(0)
    , planner_fsm(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _control_fsm_type;
  _control_fsm_type control_fsm;

   typedef int32_t _last_control_fsm_type;
  _last_control_fsm_type last_control_fsm;

   typedef uint8_t _flag_follow_tracks_plannerON_type;
  _flag_follow_tracks_plannerON_type flag_follow_tracks_plannerON;

   typedef int32_t _gear_type;
  _gear_type gear;

   typedef int32_t _planner_fsm_type;
  _planner_fsm_type planner_fsm;





  typedef boost::shared_ptr< ::control_msgs::ControlFSM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::ControlFSM_<ContainerAllocator> const> ConstPtr;

}; // struct ControlFSM_

typedef ::control_msgs::ControlFSM_<std::allocator<void> > ControlFSM;

typedef boost::shared_ptr< ::control_msgs::ControlFSM > ControlFSMPtr;
typedef boost::shared_ptr< ::control_msgs::ControlFSM const> ControlFSMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::ControlFSM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::ControlFSM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_msgs': ['/home/oligay_61/zone3/src/message/control_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ControlFSM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ControlFSM_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ControlFSM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ControlFSM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ControlFSM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ControlFSM_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::ControlFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03aa97f9d8b6f93933703b58d329f026";
  }

  static const char* value(const ::control_msgs::ControlFSM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03aa97f9d8b6f939ULL;
  static const uint64_t static_value2 = 0x33703b58d329f026ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::ControlFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/ControlFSM";
  }

  static const char* value(const ::control_msgs::ControlFSM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::ControlFSM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int32 control_fsm\n\
int32 last_control_fsm\n\
bool flag_follow_tracks_plannerON\n\
int32 gear\n\
int32 planner_fsm\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::control_msgs::ControlFSM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::ControlFSM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control_fsm);
      stream.next(m.last_control_fsm);
      stream.next(m.flag_follow_tracks_plannerON);
      stream.next(m.gear);
      stream.next(m.planner_fsm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlFSM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::ControlFSM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::ControlFSM_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control_fsm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.control_fsm);
    s << indent << "last_control_fsm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.last_control_fsm);
    s << indent << "flag_follow_tracks_plannerON: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag_follow_tracks_plannerON);
    s << indent << "gear: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gear);
    s << indent << "planner_fsm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.planner_fsm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_CONTROLFSM_H
