// Generated by gencpp from file tli65_can_msgs/ContainerCalib.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_CONTAINERCALIB_H
#define TLI65_CAN_MSGS_MESSAGE_CONTAINERCALIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct ContainerCalib_
{
  typedef ContainerCalib_<ContainerAllocator> Type;

  ContainerCalib_()
    : header()
    , pitch_degree(0.0)
    , relative_container_angle(0.0)
    , k_before_carr_angle(0.0)  {
    }
  ContainerCalib_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pitch_degree(0.0)
    , relative_container_angle(0.0)
    , k_before_carr_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _pitch_degree_type;
  _pitch_degree_type pitch_degree;

   typedef double _relative_container_angle_type;
  _relative_container_angle_type relative_container_angle;

   typedef double _k_before_carr_angle_type;
  _k_before_carr_angle_type k_before_carr_angle;





  typedef boost::shared_ptr< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> const> ConstPtr;

}; // struct ContainerCalib_

typedef ::tli65_can_msgs::ContainerCalib_<std::allocator<void> > ContainerCalib;

typedef boost::shared_ptr< ::tli65_can_msgs::ContainerCalib > ContainerCalibPtr;
typedef boost::shared_ptr< ::tli65_can_msgs::ContainerCalib const> ContainerCalibConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1e2d137e4598c60731ef7b598273d26";
  }

  static const char* value(const ::tli65_can_msgs::ContainerCalib_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1e2d137e4598c60ULL;
  static const uint64_t static_value2 = 0x731ef7b598273d26ULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/ContainerCalib";
  }

  static const char* value(const ::tli65_can_msgs::ContainerCalib_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 pitch_degree\n\
float64 relative_container_angle\n\
float64 k_before_carr_angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::ContainerCalib_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pitch_degree);
      stream.next(m.relative_container_angle);
      stream.next(m.k_before_carr_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContainerCalib_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::ContainerCalib_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::ContainerCalib_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pitch_degree: ";
    Printer<double>::stream(s, indent + "  ", v.pitch_degree);
    s << indent << "relative_container_angle: ";
    Printer<double>::stream(s, indent + "  ", v.relative_container_angle);
    s << indent << "k_before_carr_angle: ";
    Printer<double>::stream(s, indent + "  ", v.k_before_carr_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_CONTAINERCALIB_H
