// Generated by gencpp from file tli65_can_msgs/RxFuel.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_RXFUEL_H
#define TLI65_CAN_MSGS_MESSAGE_RXFUEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct RxFuel_
{
  typedef RxFuel_<ContainerAllocator> Type;

  RxFuel_()
    : header()
    , fuel_consumption(0)
    , ins_fuel_consumption(0)  {
    }
  RxFuel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fuel_consumption(0)
    , ins_fuel_consumption(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _fuel_consumption_type;
  _fuel_consumption_type fuel_consumption;

   typedef uint16_t _ins_fuel_consumption_type;
  _ins_fuel_consumption_type ins_fuel_consumption;





  typedef boost::shared_ptr< ::tli65_can_msgs::RxFuel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::RxFuel_<ContainerAllocator> const> ConstPtr;

}; // struct RxFuel_

typedef ::tli65_can_msgs::RxFuel_<std::allocator<void> > RxFuel;

typedef boost::shared_ptr< ::tli65_can_msgs::RxFuel > RxFuelPtr;
typedef boost::shared_ptr< ::tli65_can_msgs::RxFuel const> RxFuelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::RxFuel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxFuel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxFuel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxFuel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "846c3d8c296609ca08f2215de0373f81";
  }

  static const char* value(const ::tli65_can_msgs::RxFuel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x846c3d8c296609caULL;
  static const uint64_t static_value2 = 0x08f2215de0373f81ULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/RxFuel";
  }

  static const char* value(const ::tli65_can_msgs::RxFuel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint16 fuel_consumption\n\
uint16 ins_fuel_consumption\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::RxFuel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fuel_consumption);
      stream.next(m.ins_fuel_consumption);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RxFuel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::RxFuel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::RxFuel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fuel_consumption: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.fuel_consumption);
    s << indent << "ins_fuel_consumption: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ins_fuel_consumption);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_RXFUEL_H
