// Generated by gencpp from file tli65_can_msgs/RxSt3.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_RXST3_H
#define TLI65_CAN_MSGS_MESSAGE_RXST3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct RxSt3_
{
  typedef RxSt3_<ContainerAllocator> Type;

  RxSt3_()
    : header()
    , brake_pedal_pos(0.0)
    , check_sum(0)
    , msg_count(0)  {
    }
  RxSt3_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , brake_pedal_pos(0.0)
    , check_sum(0)
    , msg_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _brake_pedal_pos_type;
  _brake_pedal_pos_type brake_pedal_pos;

   typedef uint8_t _check_sum_type;
  _check_sum_type check_sum;

   typedef uint8_t _msg_count_type;
  _msg_count_type msg_count;





  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt3_<ContainerAllocator> const> ConstPtr;

}; // struct RxSt3_

typedef ::tli65_can_msgs::RxSt3_<std::allocator<void> > RxSt3;

typedef boost::shared_ptr< ::tli65_can_msgs::RxSt3 > RxSt3Ptr;
typedef boost::shared_ptr< ::tli65_can_msgs::RxSt3 const> RxSt3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::RxSt3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt3_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt3_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "212d091e04d72844ef8a23023c5cba15";
  }

  static const char* value(const ::tli65_can_msgs::RxSt3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x212d091e04d72844ULL;
  static const uint64_t static_value2 = 0xef8a23023c5cba15ULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/RxSt3";
  }

  static const char* value(const ::tli65_can_msgs::RxSt3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 brake_pedal_pos\n\
uint8 check_sum\n\
uint8 msg_count\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::RxSt3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.brake_pedal_pos);
      stream.next(m.check_sum);
      stream.next(m.msg_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RxSt3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::RxSt3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::RxSt3_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brake_pedal_pos: ";
    Printer<double>::stream(s, indent + "  ", v.brake_pedal_pos);
    s << indent << "check_sum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check_sum);
    s << indent << "msg_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_RXST3_H
