// Generated by gencpp from file tli65_can_msgs/RxSt7.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_RXST7_H
#define TLI65_CAN_MSGS_MESSAGE_RXST7_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct RxSt7_
{
  typedef RxSt7_<ContainerAllocator> Type;

  RxSt7_()
    : header()
    , left_light(0)
    , right_light(0)
    , near_light(0)
    , far_light(0)
    , top_warning_light(0)
    , air_beep(0)
    , front_fog_light(0)
    , front_work_light(0)
    , side_light(0)
    , position_light(0)
    , sweeper_power(0)
    , EBS_power(0)
    , air_pressure_power(0)
    , hang_up_power(0)
    , hang_down_power(0)
    , hang_manual_power(0)  {
    }
  RxSt7_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_light(0)
    , right_light(0)
    , near_light(0)
    , far_light(0)
    , top_warning_light(0)
    , air_beep(0)
    , front_fog_light(0)
    , front_work_light(0)
    , side_light(0)
    , position_light(0)
    , sweeper_power(0)
    , EBS_power(0)
    , air_pressure_power(0)
    , hang_up_power(0)
    , hang_down_power(0)
    , hang_manual_power(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _left_light_type;
  _left_light_type left_light;

   typedef uint8_t _right_light_type;
  _right_light_type right_light;

   typedef uint8_t _near_light_type;
  _near_light_type near_light;

   typedef uint8_t _far_light_type;
  _far_light_type far_light;

   typedef uint8_t _top_warning_light_type;
  _top_warning_light_type top_warning_light;

   typedef uint8_t _air_beep_type;
  _air_beep_type air_beep;

   typedef uint8_t _front_fog_light_type;
  _front_fog_light_type front_fog_light;

   typedef uint8_t _front_work_light_type;
  _front_work_light_type front_work_light;

   typedef uint8_t _side_light_type;
  _side_light_type side_light;

   typedef uint8_t _position_light_type;
  _position_light_type position_light;

   typedef uint8_t _sweeper_power_type;
  _sweeper_power_type sweeper_power;

   typedef uint8_t _EBS_power_type;
  _EBS_power_type EBS_power;

   typedef uint8_t _air_pressure_power_type;
  _air_pressure_power_type air_pressure_power;

   typedef uint8_t _hang_up_power_type;
  _hang_up_power_type hang_up_power;

   typedef uint8_t _hang_down_power_type;
  _hang_down_power_type hang_down_power;

   typedef uint8_t _hang_manual_power_type;
  _hang_manual_power_type hang_manual_power;





  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt7_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt7_<ContainerAllocator> const> ConstPtr;

}; // struct RxSt7_

typedef ::tli65_can_msgs::RxSt7_<std::allocator<void> > RxSt7;

typedef boost::shared_ptr< ::tli65_can_msgs::RxSt7 > RxSt7Ptr;
typedef boost::shared_ptr< ::tli65_can_msgs::RxSt7 const> RxSt7ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::RxSt7_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt7_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt7_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt7_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a534ca6f7b38ad0e102e1d9218e5253e";
  }

  static const char* value(const ::tli65_can_msgs::RxSt7_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa534ca6f7b38ad0eULL;
  static const uint64_t static_value2 = 0x102e1d9218e5253eULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/RxSt7";
  }

  static const char* value(const ::tli65_can_msgs::RxSt7_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint8 left_light\n\
uint8 right_light\n\
uint8 near_light\n\
uint8 far_light\n\
uint8 top_warning_light\n\
uint8 air_beep\n\
uint8 front_fog_light\n\
uint8 front_work_light\n\
uint8 side_light\n\
uint8 position_light\n\
uint8 sweeper_power\n\
uint8 EBS_power\n\
uint8 air_pressure_power\n\
uint8 hang_up_power\n\
uint8 hang_down_power\n\
uint8 hang_manual_power\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::RxSt7_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_light);
      stream.next(m.right_light);
      stream.next(m.near_light);
      stream.next(m.far_light);
      stream.next(m.top_warning_light);
      stream.next(m.air_beep);
      stream.next(m.front_fog_light);
      stream.next(m.front_work_light);
      stream.next(m.side_light);
      stream.next(m.position_light);
      stream.next(m.sweeper_power);
      stream.next(m.EBS_power);
      stream.next(m.air_pressure_power);
      stream.next(m.hang_up_power);
      stream.next(m.hang_down_power);
      stream.next(m.hang_manual_power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RxSt7_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::RxSt7_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::RxSt7_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_light);
    s << indent << "right_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_light);
    s << indent << "near_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.near_light);
    s << indent << "far_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.far_light);
    s << indent << "top_warning_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.top_warning_light);
    s << indent << "air_beep: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.air_beep);
    s << indent << "front_fog_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_fog_light);
    s << indent << "front_work_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.front_work_light);
    s << indent << "side_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.side_light);
    s << indent << "position_light: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.position_light);
    s << indent << "sweeper_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sweeper_power);
    s << indent << "EBS_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EBS_power);
    s << indent << "air_pressure_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.air_pressure_power);
    s << indent << "hang_up_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hang_up_power);
    s << indent << "hang_down_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hang_down_power);
    s << indent << "hang_manual_power: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hang_manual_power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_RXST7_H
