// Generated by gencpp from file tli65_can_msgs/RxSt6.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_RXST6_H
#define TLI65_CAN_MSGS_MESSAGE_RXST6_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct RxSt6_
{
  typedef RxSt6_<ContainerAllocator> Type;

  RxSt6_()
    : header()
    , gear(0)
    , max_forward_gear(0)
    , speed_from_gear(0.0)
    , check_sum(0)
    , msg_count(0)  {
    }
  RxSt6_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gear(0)
    , max_forward_gear(0)
    , speed_from_gear(0.0)
    , check_sum(0)
    , msg_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _gear_type;
  _gear_type gear;

   typedef int8_t _max_forward_gear_type;
  _max_forward_gear_type max_forward_gear;

   typedef double _speed_from_gear_type;
  _speed_from_gear_type speed_from_gear;

   typedef uint8_t _check_sum_type;
  _check_sum_type check_sum;

   typedef uint8_t _msg_count_type;
  _msg_count_type msg_count;





  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt6_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt6_<ContainerAllocator> const> ConstPtr;

}; // struct RxSt6_

typedef ::tli65_can_msgs::RxSt6_<std::allocator<void> > RxSt6;

typedef boost::shared_ptr< ::tli65_can_msgs::RxSt6 > RxSt6Ptr;
typedef boost::shared_ptr< ::tli65_can_msgs::RxSt6 const> RxSt6ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::RxSt6_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt6_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt6_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt6_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e92144d475c554c1ac37c95adff72a8";
  }

  static const char* value(const ::tli65_can_msgs::RxSt6_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e92144d475c554cULL;
  static const uint64_t static_value2 = 0x1ac37c95adff72a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/RxSt6";
  }

  static const char* value(const ::tli65_can_msgs::RxSt6_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int8 gear\n\
int8 max_forward_gear\n\
float64 speed_from_gear\n\
uint8 check_sum\n\
uint8 msg_count\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::RxSt6_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gear);
      stream.next(m.max_forward_gear);
      stream.next(m.speed_from_gear);
      stream.next(m.check_sum);
      stream.next(m.msg_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RxSt6_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::RxSt6_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::RxSt6_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "max_forward_gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.max_forward_gear);
    s << indent << "speed_from_gear: ";
    Printer<double>::stream(s, indent + "  ", v.speed_from_gear);
    s << indent << "check_sum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check_sum);
    s << indent << "msg_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_RXST6_H
