// Generated by gencpp from file tli65_can_msgs/RxSt2.msg
// DO NOT EDIT!


#ifndef TLI65_CAN_MSGS_MESSAGE_RXST2_H
#define TLI65_CAN_MSGS_MESSAGE_RXST2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tli65_can_msgs
{
template <class ContainerAllocator>
struct RxSt2_
{
  typedef RxSt2_<ContainerAllocator> Type;

  RxSt2_()
    : header()
    , throttle_pedal_pos(0.0)
    , engine_torque_percentage(0.0)
    , engine_speed(0.0)
    , actual_throttle_pedal_pos(0.0)
    , check_sum(0)
    , msg_count(0)  {
    }
  RxSt2_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle_pedal_pos(0.0)
    , engine_torque_percentage(0.0)
    , engine_speed(0.0)
    , actual_throttle_pedal_pos(0.0)
    , check_sum(0)
    , msg_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _throttle_pedal_pos_type;
  _throttle_pedal_pos_type throttle_pedal_pos;

   typedef double _engine_torque_percentage_type;
  _engine_torque_percentage_type engine_torque_percentage;

   typedef double _engine_speed_type;
  _engine_speed_type engine_speed;

   typedef double _actual_throttle_pedal_pos_type;
  _actual_throttle_pedal_pos_type actual_throttle_pedal_pos;

   typedef uint8_t _check_sum_type;
  _check_sum_type check_sum;

   typedef uint8_t _msg_count_type;
  _msg_count_type msg_count;





  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tli65_can_msgs::RxSt2_<ContainerAllocator> const> ConstPtr;

}; // struct RxSt2_

typedef ::tli65_can_msgs::RxSt2_<std::allocator<void> > RxSt2;

typedef boost::shared_ptr< ::tli65_can_msgs::RxSt2 > RxSt2Ptr;
typedef boost::shared_ptr< ::tli65_can_msgs::RxSt2 const> RxSt2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tli65_can_msgs::RxSt2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tli65_can_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_msgs': ['/opt/ros/kinetic/share/can_msgs/cmake/../msg'], 'tli65_can_msgs': ['/home/oligay_61/zone3/src/message/tli65_can_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tli65_can_msgs::RxSt2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tli65_can_msgs::RxSt2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tli65_can_msgs::RxSt2_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938cd4fdf7b654ca0e40be74922e1cc4";
  }

  static const char* value(const ::tli65_can_msgs::RxSt2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938cd4fdf7b654caULL;
  static const uint64_t static_value2 = 0x0e40be74922e1cc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tli65_can_msgs/RxSt2";
  }

  static const char* value(const ::tli65_can_msgs::RxSt2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 throttle_pedal_pos\n\
float64 engine_torque_percentage\n\
float64 engine_speed\n\
float64 actual_throttle_pedal_pos\n\
uint8 check_sum\n\
uint8 msg_count\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tli65_can_msgs::RxSt2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle_pedal_pos);
      stream.next(m.engine_torque_percentage);
      stream.next(m.engine_speed);
      stream.next(m.actual_throttle_pedal_pos);
      stream.next(m.check_sum);
      stream.next(m.msg_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RxSt2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tli65_can_msgs::RxSt2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tli65_can_msgs::RxSt2_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle_pedal_pos: ";
    Printer<double>::stream(s, indent + "  ", v.throttle_pedal_pos);
    s << indent << "engine_torque_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.engine_torque_percentage);
    s << indent << "engine_speed: ";
    Printer<double>::stream(s, indent + "  ", v.engine_speed);
    s << indent << "actual_throttle_pedal_pos: ";
    Printer<double>::stream(s, indent + "  ", v.actual_throttle_pedal_pos);
    s << indent << "check_sum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check_sum);
    s << indent << "msg_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.msg_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TLI65_CAN_MSGS_MESSAGE_RXST2_H
