(cl:in-package localization_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RTK_STATE-VAL
          RTK_STATE
          LAT-VAL
          LAT
          LNG-VAL
          LNG
          ALT-VAL
          ALT
          LATLNG_STD-VAL
          LATLNG_STD
          X_ENU-VAL
          X_ENU
          Y_ENU-VAL
          Y_ENU
          Z_ENU-VAL
          Z_ENU
          XY_STD_ENU-VAL
          XY_STD_ENU
          VX_EGO-VAL
          VX_EGO
          VY_EGO-VAL
          VY_EGO
          VZ_EGO-VAL
          VZ_EGO
          SPEED-VAL
          SPEED
          AX_EGO-VAL
          AX_EGO
          AY_EGO-VAL
          AY_EGO
          AZ_EGO-VAL
          AZ_EGO
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          YAW_RATE-VAL
          YAW_RATE
          ORIENTATION-VAL
          ORIENTATION
))