// Generated by gencpp from file g29_teledrive_msgs/G29_teledrive.msg
// DO NOT EDIT!


#ifndef G29_TELEDRIVE_MSGS_MESSAGE_G29_TELEDRIVE_H
#define G29_TELEDRIVE_MSGS_MESSAGE_G29_TELEDRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace g29_teledrive_msgs
{
template <class ContainerAllocator>
struct G29_teledrive_
{
  typedef G29_teledrive_<ContainerAllocator> Type;

  G29_teledrive_()
    : header()
    , steer(0.0)
    , throttle(0.0)
    , xbr(0.0)
    , hang(0.0)
    , epb(0)
    , gear(0)  {
    }
  G29_teledrive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steer(0.0)
    , throttle(0.0)
    , xbr(0.0)
    , hang(0.0)
    , epb(0)
    , gear(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _steer_type;
  _steer_type steer;

   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _xbr_type;
  _xbr_type xbr;

   typedef double _hang_type;
  _hang_type hang;

   typedef int8_t _epb_type;
  _epb_type epb;

   typedef int8_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> const> ConstPtr;

}; // struct G29_teledrive_

typedef ::g29_teledrive_msgs::G29_teledrive_<std::allocator<void> > G29_teledrive;

typedef boost::shared_ptr< ::g29_teledrive_msgs::G29_teledrive > G29_teledrivePtr;
typedef boost::shared_ptr< ::g29_teledrive_msgs::G29_teledrive const> G29_teledriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace g29_teledrive_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'g29_teledrive_msgs': ['/home/oligay_61/zone3/src/message/g29_teledrive_msgs/msg', '/home/oligay_61/zone3/src/message/g29_teledrive_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "499a726284cbe0d6a1daa981a1060bff";
  }

  static const char* value(const ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x499a726284cbe0d6ULL;
  static const uint64_t static_value2 = 0xa1daa981a1060bffULL;
};

template<class ContainerAllocator>
struct DataType< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "g29_teledrive_msgs/G29_teledrive";
  }

  static const char* value(const ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 steer\n\
float64 throttle\n\
float64 xbr\n\
float64 hang\n\
int8 epb\n\
int8 gear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steer);
      stream.next(m.throttle);
      stream.next(m.xbr);
      stream.next(m.hang);
      stream.next(m.epb);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct G29_teledrive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::g29_teledrive_msgs::G29_teledrive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steer: ";
    Printer<double>::stream(s, indent + "  ", v.steer);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "xbr: ";
    Printer<double>::stream(s, indent + "  ", v.xbr);
    s << indent << "hang: ";
    Printer<double>::stream(s, indent + "  ", v.hang);
    s << indent << "epb: ";
    Printer<int8_t>::stream(s, indent + "  ", v.epb);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // G29_TELEDRIVE_MSGS_MESSAGE_G29_TELEDRIVE_H
