(cl:in-package control_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HANDS-VAL
          HANDS
          EPB_ACTIVE-VAL
          EPB_ACTIVE
          EPB-VAL
          EPB
          RETARDER_ACTIVE-VAL
          RETARDER_ACTIVE
          RETARDER-VAL
          RETARDER
          GEAR_ACTIVE-VAL
          GEAR_ACTIVE
          MAX_FORWARD_GEAR-VAL
          MAX_FORWARD_GEAR
          GEAR-VAL
          GEAR
          HANG_ACTIVE-VAL
          HANG_ACTIVE
          HANG-VAL
          HANG
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          NEAR-VAL
          NEAR
          FAR-VAL
          FAR
          TOP_WARN-VAL
          TOP_WARN
          AIR_BEEP-VAL
          AIR_BEEP
          FRONT_FOG-VAL
          FRONT_FOG
          FRONT_WORK-VAL
          FRONT_WORK
          SIDE-VAL
          SIDE
          POSITION-VAL
          POSITION
          EMERGENCY-VAL
          EMERGENCY
          BRAKE-VAL
          BRAKE
          REVERSE-VAL
          REVERSE
          BACK_WORK-VAL
          BACK_WORK
          COOLER-VAL
          COOLER
          AXLE_DIFF-VAL
          AXLE_DIFF
          EXHAUST_BRAKE-VAL
          EXHAUST_BRAKE
))