(cl:in-package teledrive_msgs-msg)
(cl:export '(CONTROL_TYPE-VAL
          CONTROL_TYPE
          STEER-VAL
          STEER
          THROTTLE_PEDAL-VAL
          THROTTLE_PEDAL
          XBR-VAL
          XBR
          GEAR-VAL
          GEAR
          EPB-VAL
          EPB
          HANG-VAL
          HANG
          AIR_BEEP-VAL
          AIR_BEEP
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          TL_ROTATE_WARNING_LIGHT-VAL
          TL_ROTATE_WARNING_LIGHT
          TL_FRONT_FOG_LIGHT-VAL
          TL_FRONT_FOG_LIGHT
          TL_FRONT_WORK_LIGHT-VAL
          TL_FRONT_WORK_LIGHT
          TL_BACK_WORK_LIGHT-VAL
          TL_BACK_WORK_LIGHT
          TL_SIDE_LIGHT-VAL
          TL_SIDE_LIGHT
          TL_BACK_POSITION_LIGHT-VAL
          TL_BACK_POSITION_LIGHT
          TL_HAZARD_INDICATOR_LIGHT-VAL
          TL_HAZARD_INDICATOR_LIGHT
          TL_BRAKE_LIGHT-VAL
          TL_BRAKE_LIGHT
          TL_RETURN_LIGHT-VAL
          TL_RETURN_LIGHT
))