(cl:in-package teledrive_msgs-msg)
(cl:export '(CONTROL_TYPE-VAL
          CONTROL_TYPE
          STEER-VAL
          STEER
          THROTTLE_PEDAL-VAL
          THROTTLE_PEDAL
          XBR-VAL
          XBR
          GEAR-VAL
          GEAR
          EPB-VAL
          EPB
          HANG-VAL
          HANG
          AIR_BEEP-VAL
          AIR_BEEP
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          TOP_WARNING_LIGHT-VAL
          TOP_WARNING_LIGHT
          FRONT_FOG_LIGHT-VAL
          FRONT_FOG_LIGHT
          FRONT_WORK_LIGHT-VAL
          FRONT_WORK_LIGHT
          BACK_WORK_LIGHT-VAL
          BACK_WORK_LIGHT
          SIDE_LIGHT-VAL
          SIDE_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          EMERGENCY_LIGHT-VAL
          EMERGENCY_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          REVERSE_LIGHT-VAL
          REVERSE_LIGHT
))