(cl:in-package displaydata_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RTK_STATE-VAL
          RTK_STATE
          LAT-VAL
          LAT
          LNG-VAL
          LNG
          ALT-VAL
          ALT
          LATLNG_STD-VAL
          LATLNG_STD
          X_ENU-VAL
          X_ENU
          Y_ENU-VAL
          Y_ENU
          Z_ENU-VAL
          Z_ENU
          XY_STD_ENU-VAL
          XY_STD_ENU
          SPEED-VAL
          SPEED
          HEADINGANGLE-VAL
          HEADINGANGLE
          CURRENT_STEER-VAL
          CURRENT_STEER
          CURRENT_BRAKE_PEDAL_POS-VAL
          CURRENT_BRAKE_PEDAL_POS
          CURRENT_THROTTLE_PERCENTAGE-VAL
          CURRENT_THROTTLE_PERCENTAGE
          CURRENT_RETARDER_TORQUE_PERCENTAGE-VAL
          CURRENT_RETARDER_TORQUE_PERCENTAGE
          CURRENT_EPB-VAL
          CURRENT_EPB
          CURRENT_GEAR-VAL
          CURRENT_GEAR
          CURRENT_HANGANGLE-VAL
          CURRENT_HANGANGLE
          AUTO_MODE-VAL
          AUTO_MODE
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          AIR_BEEP-VAL
          AIR_BEEP
          TOP_WARNING_LIGHT-VAL
          TOP_WARNING_LIGHT
          FRONT_FOG_LIGHT-VAL
          FRONT_FOG_LIGHT
          FRONT_WORK_LIGHT-VAL
          FRONT_WORK_LIGHT
          SIDE_LIGHT-VAL
          SIDE_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          BACK_LEFT_LIGHT-VAL
          BACK_LEFT_LIGHT
          BACK_RIGHT_LIGHT-VAL
          BACK_RIGHT_LIGHT
          BACK_POSITION_LIGHT-VAL
          BACK_POSITION_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          REVERSE_LIGHT-VAL
          REVERSE_LIGHT
          BACK_WORK_LIGHT-VAL
          BACK_WORK_LIGHT
          CONTROL_STEER-VAL
          CONTROL_STEER
          CONTROL_THROTTLE_PERCENTAGE-VAL
          CONTROL_THROTTLE_PERCENTAGE
          CONTROL_XBR-VAL
          CONTROL_XBR
          CONTROL_EPB-VAL
          CONTROL_EPB
          CONTROL_GEAR-VAL
          CONTROL_GEAR
          CONTROL_HANG-VAL
          CONTROL_HANG
          CONTROL_FSM_STATE-VAL
          CONTROL_FSM_STATE
          LEFT-VAL
          LEFT
          RIGHT-VAL
          RIGHT
          NEAR-VAL
          NEAR
          FAR-VAL
          FAR
          TOP_WARN-VAL
          TOP_WARN
          CONTROL_AIR_BEEP-VAL
          CONTROL_AIR_BEEP
          FRONT_FOG-VAL
          FRONT_FOG
          FRONT_WORK-VAL
          FRONT_WORK
          SIDE-VAL
          SIDE
          POSITION-VAL
          POSITION
          EMERGENCY-VAL
          EMERGENCY
          BRAKE-VAL
          BRAKE
          REVERSE-VAL
          REVERSE
          BACK_WORK-VAL
          BACK_WORK
          TARGET_X-VAL
          TARGET_X
          TARGET_Y-VAL
          TARGET_Y
          NUMSATE-VAL
          NUMSATE
          ENGINE_FAULT-VAL
          ENGINE_FAULT
          GEAR_FAULT-VAL
          GEAR_FAULT
          EBS_FAULT-VAL
          EBS_FAULT
          EPS_FAULT-VAL
          EPS_FAULT
          EPB_FAULT-VAL
          EPB_FAULT
          TRUCK_FAULT_LEVEL-VAL
          TRUCK_FAULT_LEVEL
          ENGINE_FAULT_CODE-VAL
          ENGINE_FAULT_CODE
          GEAR_FAULT_CODE-VAL
          GEAR_FAULT_CODE
          EPS_FAULT_CODE-VAL
          EPS_FAULT_CODE
          EBS_FAULT_CODE-VAL
          EBS_FAULT_CODE
          ELECTRIC_FAULT_CODE-VAL
          ELECTRIC_FAULT_CODE
          TYRE_PRESSURE_LEFTFRONT-VAL
          TYRE_PRESSURE_LEFTFRONT
          TYRE_PRESSURE_RIGHTFRONT-VAL
          TYRE_PRESSURE_RIGHTFRONT
          FRONT_LEFT_TEMPERATURE-VAL
          FRONT_LEFT_TEMPERATURE
          FRONT_RIGHT_TEMPERATURE-VAL
          FRONT_RIGHT_TEMPERATURE
))