(cl:in-package displaydata_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          RTK_STATE-VAL
          RTK_STATE
          LAT-VAL
          LAT
          LNG-VAL
          LNG
          ALT-VAL
          ALT
          X_ENU-VAL
          X_ENU
          Y_ENU-VAL
          Y_ENU
          Z_ENU-VAL
          Z_ENU
          XY_STD_ENU-VAL
          XY_STD_ENU
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          NUMSATE-VAL
          NUMSATE
          VX-VAL
          VX
          AUTO_MODE-VAL
          AUTO_MODE
          CURRENT_STEER-VAL
          CURRENT_STEER
          CURRENT_BRAKE_PEDAL_POS-VAL
          CURRENT_BRAKE_PEDAL_POS
          CURRENT_THROTTLE_PERCENTAGE-VAL
          CURRENT_THROTTLE_PERCENTAGE
          CURRENT_RETARDER_TORQUE_PERCENTAGE-VAL
          CURRENT_RETARDER_TORQUE_PERCENTAGE
          CURRENT_EPB-VAL
          CURRENT_EPB
          CURRENT_GEAR-VAL
          CURRENT_GEAR
          CURRENT_HANG_ANGLE-VAL
          CURRENT_HANG_ANGLE
          AIR_PRESSURE1-VAL
          AIR_PRESSURE1
          AIR_PRESSURE2-VAL
          AIR_PRESSURE2
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          AIR_BEEP-VAL
          AIR_BEEP
          TOP_WARNING_LIGHT-VAL
          TOP_WARNING_LIGHT
          FRONT_FOG_LIGHT-VAL
          FRONT_FOG_LIGHT
          FRONT_WORK_LIGHT-VAL
          FRONT_WORK_LIGHT
          SIDE_LIGHT-VAL
          SIDE_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          BACK_LEFT_LIGHT-VAL
          BACK_LEFT_LIGHT
          BACK_RIGHT_LIGHT-VAL
          BACK_RIGHT_LIGHT
          BACK_POSITION_LIGHT-VAL
          BACK_POSITION_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          REVERSE_LIGHT-VAL
          REVERSE_LIGHT
          BACK_WORK_LIGHT-VAL
          BACK_WORK_LIGHT
          FUEL_CONSUMPTION-VAL
          FUEL_CONSUMPTION
          PLANNER_FSM_STATE-VAL
          PLANNER_FSM_STATE
          LOCK_DOWN_INDEX-VAL
          LOCK_DOWN_INDEX
          PT_INDEX-VAL
          PT_INDEX
          WPT_X-VAL
          WPT_X
          WPT_Y-VAL
          WPT_Y
          CONTROL_FSM_STATE-VAL
          CONTROL_FSM_STATE
          CONTROL_STEER-VAL
          CONTROL_STEER
          CONTROL_THROTTLE_PERCENTAGE-VAL
          CONTROL_THROTTLE_PERCENTAGE
          CONTROL_XBR-VAL
          CONTROL_XBR
          CONTROL_EPB-VAL
          CONTROL_EPB
          CONTROL_GEAR-VAL
          CONTROL_GEAR
          CONTROL_HANG-VAL
          CONTROL_HANG
          ENGINE_FAULT-VAL
          ENGINE_FAULT
          GEAR_FAULT-VAL
          GEAR_FAULT
          EBS_FAULT-VAL
          EBS_FAULT
          EPS_FAULT-VAL
          EPS_FAULT
          EPB_FAULT-VAL
          EPB_FAULT
          TYRE_PRESSURE_LEFTFRONT-VAL
          TYRE_PRESSURE_LEFTFRONT
          TYRE_PRESSURE_RIGHTFRONT-VAL
          TYRE_PRESSURE_RIGHTFRONT
          FRONT_LEFT_TEMPERATURE-VAL
          FRONT_LEFT_TEMPERATURE
          FRONT_RIGHT_TEMPERATURE-VAL
          FRONT_RIGHT_TEMPERATURE
))