(cl:in-package frontend_msgs-msg)
(cl:export '(LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          NEAR_LIGHT-VAL
          NEAR_LIGHT
          FAR_LIGHT-VAL
          FAR_LIGHT
          TOP_WARNING_LIGHT-VAL
          TOP_WARNING_LIGHT
          AIR_BEEP-VAL
          AIR_BEEP
          FRONT_FOG_LIGHT-VAL
          FRONT_FOG_LIGHT
          FRONT_WORK_LIGHT-VAL
          FRONT_WORK_LIGHT
          SIDE_LIGHT-VAL
          SIDE_LIGHT
          POSITION_LIGHT-VAL
          POSITION_LIGHT
          BACK_LEFT_LIGHT-VAL
          BACK_LEFT_LIGHT
          BACK_RIGHT_LIGHT-VAL
          BACK_RIGHT_LIGHT
          BACK_POSITION_LIGHT-VAL
          BACK_POSITION_LIGHT
          BRAKE_LIGHT-VAL
          BRAKE_LIGHT
          REVERSE_LIGHT-VAL
          REVERSE_LIGHT
          BACK_WORK_LIGHT-VAL
          BACK_WORK_LIGHT
))