(cl:in-package planner_msgs-msg)
(cl:export '(LOCK_DOWN_INDEX-VAL
          LOCK_DOWN_INDEX
          PT_INDEX-VAL
          PT_INDEX
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          KALMAN_YAWRATE-VAL
          KALMAN_YAWRATE
          KALMAN_VX-VAL
          KALMAN_VX
          ACCELERATION-VAL
          ACCELERATION
          STEER-VAL
          STEER
          THROTTLE_PERCENTAGE-VAL
          THROTTLE_PERCENTAGE
          XBR-VAL
          XBR
          GEAR-VAL
          GEAR
          LEFT_LIGHT-VAL
          LEFT_LIGHT
          RIGHT_LIGHT-VAL
          RIGHT_LIGHT
          AIR_BEEP-VAL
          AIR_BEEP
          TIME_TO_LAST_POINT-VAL
          TIME_TO_LAST_POINT
          CURRENT_LAT_ERROR-VAL
          CURRENT_LAT_ERROR
          CURRENT_LNG_ERROR-VAL
          CURRENT_LNG_ERROR
          FLAG_LOCK_DOWN_INDEX_OFFLOAD-VAL
          FLAG_LOCK_DOWN_INDEX_OFFLOAD
))