Header header

string hands

uint8 EPB_active 
uint8 EPB
uint8 retarder_active
float64 retarder
uint8 gear_active
uint8 max_forward_gear
uint8 gear
uint8 hang_active
uint8 hang

# body switch
uint8 left
uint8 right
uint8 near
uint8 far
uint8 top_warn
uint8 air_beep
uint8 front_fog
uint8 front_work
uint8 side
uint8 position
uint8 emergency
uint8 brake
uint8 reverse
uint8 back_work
uint8 cooler
uint8 axle_diff
uint8 exhaust_brake