string control_type

float64 steer
float64 throttle_pedal
float64 xbr
int32 gear
int32 epb
int32 hang
bool air_beep
bool left_light
bool right_light
bool near_light
bool far_light

#TL lights state
bool TL_rotate_warning_light
bool TL_front_fog_light
bool TL_front_work_light
bool TL_back_work_light
bool TL_side_light
bool TL_back_position_light
bool TL_hazard_indicator_light
bool TL_brake_light
bool TL_return_light